### ISSUE TITLE
[Bug]: Bottom navigation items color in light theme

### ISSUE THREAD

**Issue by cdhiraj40** [cdhiraj40/mobile-dapp-scaffold#3]
**Describe the bug**

**To Reproduce**
1. Open the app
2. Observe the bottom navigation menu and that the not-selected items are difficult to see due to the dark background.

**Expected behavior**
The bottom navigation items should be visible and easy to distinguish, regardless of the selected theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/75211982/232597472-e68464a6-811b-4b3f-949a-3c1082b92311.png)

**Comment by SanjaySargam** [comment]
I would love to work on this issue

**Comment by sanjaysargam** [comment]
I would like to work on this issue
